name: chocolatine

on:
  push:
    branches-ignore:
      - ga-ignore-**
  pull_request:
    branches-ignore:
      - ga-ignore-**
env:
  - MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-REN-2-1-bschocolatine-axel.wiemert.git
  - EXECUTABLES: my_rpg,lem-in

jobs:
  check_repository_cleaniness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          

  check_program_compilation:
    needs: check_repository_cleaniness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

  push_to_mirror:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0